[package]
name = "tesseruct"
version = "0.1.0"
authors = ["Hiroshi Hatake <cosmo0920.wp@gmail.com>"]

[dependencies]
libc = "~0.2.0"

[dependencies.tesseruct_sys]
version = "~0.1.0"
path = "tesseruct_sys"